name: pytest

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: '3.11'
            pyspark: '3.5.4'
            java: '11'
            jpmml-evaluator-spark-packages: 'org.jpmml:jpmml-evaluator-spark:2.0.2'
          - python: '3.13'
            pyspark: '4.1.0'
            java: '17'
            jpmml-evaluator-spark-packages: 'org.jpmml:jpmml-evaluator-spark:2.1.2'

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java }}
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
        cache: 'pip'
    - run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pyspark==${{ matrix.pyspark }}
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - run: |
        python -m pytest
      env:
        JPMML_EVALUATOR_SPARK_PACKAGES: ${{ matrix.jpmml-evaluator-spark-packages }}
